server:
  port: 9087
spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: news-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
  redis:
    host: localhost
    port: 6379
    timeout: 5s